"""add favorites table

Revision ID: 797b5ae947f2
Revises: 61624933706d
Create Date: 2026-08-01 17:00:08.727198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797b5ae947f2'
down_revision: Union[str, Sequence[str], None] = '61624933706d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favourites_room_id'), 'favourites', ['room_id'], unique=False)
    op.create_index(op.f('ix_favourites_user_id'), 'favourites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favourites_user_id'), table_name='favourites')
    op.drop_index(op.f('ix_favourites_room_id'), table_name='favourites')
    op.drop_table('favourites')
    # ### end Alembic commands ###
