"""add created_at and updated_at

Revision ID: bc4a2ea1f972
Revises: 
Create Date: 2026-07-20 23:12:56.937196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4a2ea1f972'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('bookings', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('bookings', 'guest_count',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index(op.f('ix_bookings_date_in'), 'bookings', ['date_in'], unique=False)
    op.create_index(op.f('ix_bookings_date_out'), 'bookings', ['date_out'], unique=False)
    op.create_index(op.f('ix_bookings_room_id'), 'bookings', ['room_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.add_column('rooms', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('rooms', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('rooms', 'capacity',
               existing_type=sa.NUMERIC(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.alter_column('rooms', 'capacity',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('rooms', 'updated_at')
    op.drop_column('rooms', 'created_at')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_room_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_date_out'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_date_in'), table_name='bookings')
    op.alter_column('bookings', 'guest_count',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('bookings', 'updated_at')
    op.drop_column('bookings', 'created_at')
    # ### end Alembic commands ###
